import React from "react";
import {
  AiOutlineDashboard,
  AiOutlineDatabase,
  AiOutlineLayout,
} from "react-icons/ai";
import { HiOutlineAcademicCap, HiOutlineChartSquareBar } from "react-icons/hi";
import {
  RiBarChart2Line,
  RiCustomerService2Line,
  RiDashboardLine,
  RiEqualizerLine,
  RiListCheck3,
  RiShieldUserLine,
  RiTodoLine,
} from "react-icons/ri";
import {
  BiBookReader,
  BiCartAlt,
  BiData,
  BiDollar,
  BiErrorCircle,
  BiRss,
  BiSolidCategoryAlt,
  BiTask,
} from "react-icons/bi";
import {
  MdContactSupport,
  MdDevicesOther,
  MdInvertColors,
  MdOutlineAnalytics,
  MdOutlineContactPhone,
  MdOutlineContactSupport,
  MdOutlineDns,
  MdOutlineMailOutline,
  MdOutlineManageAccounts,
  MdSubject,
  MdTimeline,
} from "react-icons/md";
import { VscFeedback } from "react-icons/vsc";
import {
  BsBriefcase,
  BsCart4,
  BsChatDots,
  BsCurrencyBitcoin,
  BsQuestionDiamond,
  BsSubtract,
  BsTable,
} from "react-icons/bs";
import {
  GiCloverSpiked,
  GiPayMoney,
  GiReceiveMoney,
  GiTakeMyMoney,
} from "react-icons/gi";
import { FaRegCalendarAlt, FaRegHospital, FaRegImages } from "react-icons/fa";
import { CgAttachment, CgFeed, CgUserList } from "react-icons/cg";
import { TiMap } from "react-icons/ti";
import { FiMail, FiMap, FiUsers } from "react-icons/fi";
import { IoMdNotificationsOutline } from "react-icons/io";
import { DiHtml5Multimedia } from "react-icons/di";
import { RoutePermittedRole } from "@crema/constants/AppEnums";
import { GrUserAdmin } from "react-icons/gr";
import { TbArrowsRightLeft, TbFileInvoice } from "react-icons/tb";
import { PiWarningLight } from "react-icons/pi";
import { LiaUserShieldSolid } from "react-icons/lia";
import { SiOpenaccess } from "react-icons/si";
import { GoOrganization } from "react-icons/go";
import { CiCircleList } from "react-icons/ci";
import { IoFolderSharp, IoPricetags } from "react-icons/io5";
import { UsersRolesEnums } from "utils/common-constants.utils";

const routesConfig = [
  {
    id: "tt-dashboards",
    title: "Tam Tam Application",
    messageId: "sidebar.application",
    type: "group",
    children: [
      {
        id: "tt-home",
        title: "Tam Tam Dashbord",
        messageId: "sidebar.app.dashboard.home",
        icon: <AiOutlineDashboard />,
        permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
        path: "/dashboards/home",
      },
      {
        id: "tt-reporting",
        title: "Tam Tam Reporting",
        messageId: "common.reports",
        icon: <RiBarChart2Line />,
        permittedRole: [
          UsersRolesEnums.ADMIN,
          UsersRolesEnums.MANAGER,
          UsersRolesEnums.USER,
        ],
        path: "/dashboards/reporting",
      },
      {
        id: "tt-approvals",
        title: "Tam Tam Expenses Approvals",
        messageId: "sidebar.app.dashboard.approvals",
        icon: <RiListCheck3 />,
        permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
        path: "/dashboards/approvals",
      },
      {
        id: "tt-accounting",
        title: "Tam Tam Accounting",
        messageId: "sidebar.app.dashboard.accounting",
        icon: <GiPayMoney />,
        permittedRole: [UsersRolesEnums.ADMIN],
        path: "/dashboards/accountings",
      },
      {
        id: "tt-expenses",
        title: "Tam Tam Expenses",
        messageId: "common.expenses",
        icon: <GiReceiveMoney />,
        permittedRole: [
          UsersRolesEnums.ADMIN,
          UsersRolesEnums.MANAGER,
          UsersRolesEnums.USER,
        ],
        path: "/dashboards/expenses",
      },
      {
        id: "tt-movements",
        title: "Tam Tam Movements",
        messageId: "common.movements",
        icon: <TbArrowsRightLeft />,
        permittedRole: [UsersRolesEnums.USER],
        path: "/dashboards/movements",
      },
      {
        id: "tt-support-tickets",
        title: "Tam Tam Support Tickets",
        messageId: "common.support.ticket",
        icon: <MdContactSupport />,
        permittedRole: [UsersRolesEnums.USER],
        path: "/dashboards/help-center",
      },
      {
        id: "tt-contact-us",
        title: "Tam Tam Contact Us",
        messageId: "extraPages.contactUs",
        icon: <MdOutlineMailOutline />,
        permittedRole: [UsersRolesEnums.MANAGER, UsersRolesEnums.USER],
        path: "/dashboards/contact-us",
      },
      // {
      //   id: "crypto",
      //   title: "Crypto",
      //   messageId: "sidebar.app.dashboard.crypto",
      //   icon: <BsCurrencyBitcoin />,
      //   path: "/dashboards/crypto",
      // },
      // {
      //   id: "crm",
      //   title: "CRM",
      //   messageId: "sidebar.app.dashboard.crm",
      //   icon: <RiCustomerService2Line />,
      //   path: "/dashboards/crm",
      // },
      // {
      //   id: "analytics",
      //   title: "Analytics",
      //   messageId: "sidebar.app.dashboard.analytics",
      //   icon: <MdOutlineAnalytics />,
      //   path: "/dashboards/analytics",
      // },
      // {
      //   id: "health-care",
      //   title: "Health Care",
      //   permittedRole: RoutePermittedRole.User,
      //   messageId: "sidebar.healthCare",
      //   icon: <FaRegHospital />,
      //   path: "/dashboards/health-care",
      // },
      // {
      //   id: "e-commerce",
      //   title: "E-Commerce",
      //   messageId: "sidebar.app.dashboard.eCommerce",
      //   icon: <BsCart4 />,
      //   path: "/dashboards/e-commerce",
      // },
      // {
      //   id: "academy",
      //   title: "Academy",
      //   messageId: "sidebar.app.dashboard.academy",
      //   icon: <HiOutlineAcademicCap />,
      //   path: "/dashboards/academy",
      // },
      // {
      //   id: "metrics",
      //   title: "Metrics",
      //   messageId: "sidebar.app.metrics",
      //   icon: <HiOutlineChartSquareBar />,
      //   path: "/dashboards/metrics",
      // },
      // {
      //   id: "widgets",
      //   title: "Widgets",
      //   messageId: "sidebar.app.widgets",
      //   icon: <RiDashboardLine />,
      //   path: "/dashboards/widgets",
      // },
    ],
  },
  {
    id: "tt-administration",
    title: "Tam Tam Administration",
    messageId: "sidebar.administration",
    type: "group",
    children: [
      {
        id: "tt-recharge",
        title: "Tam Tam Recharge Solde",
        messageId: "common.recharges",
        icon: <GiTakeMyMoney />,
        permittedRole: [UsersRolesEnums.ADMIN],
        path: "/dashboards/recharges",
      },
      {
        id: "tt-users",
        title: "Tam Tam Users",
        messageId: "common.users",
        icon: <FiUsers />,
        permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
        path: "/dashboards/users",
      },
      {
        id: "tt-categories",
        title: "Tam Tam Categories",
        messageId: "common.categories",
        icon: <BiSolidCategoryAlt />,
        permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
        path: "/dashboards/categories",
      },
      {
        id: "tt-subcategories",
        title: "Tam Tam Sub Categories",
        messageId: "common.subcategories",
        icon: <BsSubtract />,
        permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
        path: "/dashboards/sub-categories",
      },
      {
        id: "tt-organizations",
        title: "Tam Tam Organizations",
        messageId: "sidebar.app.dashboard.organizations",
        icon: <GoOrganization />,
        permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
        path: "/dashboards/organisations",
      },
      {
        id: "tt-privileges",
        title: "Tam Tam Privileges",
        messageId: "sidebar.app.dashboard.privileges",
        icon: <SiOpenaccess />,
        type: "collapse",
        permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
        children: [
          {
            id: "tt-roles",
            title: "Tam Tam Roles",
            messageId: "sidebar.app.dashboard.roles",
            icon: <LiaUserShieldSolid />,
            permittedRole: [UsersRolesEnums.ADMIN],
            path: "/dashboards/privileges/roles",
          },
          {
            id: "tt-permissions",
            title: "Tam Tam Permissions",
            messageId: "sidebar.app.dashboard.permissions",
            icon: <PiWarningLight />,
            permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
            path: "/dashboards/privileges/permissions",
          },
        ],
      },
      {
        id: "tt-contacts",
        title: "Tam Tam Contacts",
        messageId: "common.contacts",
        icon: <MdOutlineContactPhone />,
        permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
        type: "collapse",
        children: [
          {
            id: "tt-contacts-list",
            title: "Tam Tam Contacts List",
            messageId: "common.alls",
            icon: <CiCircleList />,
            permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
            path: "/dashboards/contacts",
          },
          {
            id: "tt-labels",
            title: "Tam Tam Permissions",
            messageId: "common.labels",
            icon: <IoPricetags />,
            permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
            path: "/dashboards/contacts/labels",
          },
          {
            id: "tt-folders",
            title: "Tam Tam Permissions",
            messageId: "common.folders",
            icon: <IoFolderSharp />,
            permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
            path: "/dashboards/contacts/folders",
          },
        ],
      },
      {
        id: "tt-faqs",
        title: "Tam Tam Faqs",
        messageId: "sidebar.app.dashboard.faqs",
        icon: <BsQuestionDiamond />,
        type: "collapse",
        permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
        children: [
          {
            id: "tt-faqs-parent",
            title: "Tam Tam Faqs Parent",
            messageId: "sidebar.app.dashboard.faqs",
            icon: <BiSolidCategoryAlt />,
            permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
            path: "/dashboards/faqs/parent",
          },
          {
            id: "tt-faqs-child",
            title: "Tam Tam Faqs Child",
            messageId: "sidebar.app.dashboard.subfaqs",
            icon: <BsSubtract />,
            permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
            path: "/dashboards/faqs/children",
          },
        ],
      },
      {
        id: "tt-help-center",
        title: "Tam Tam Help Center",
        messageId: "common.support",
        icon: <MdContactSupport />,
        type: "collapse",
        permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
        children: [
          {
            id: "tt-help-center-list",
            title: "Tam Tam Help Center List",
            messageId: "common.alls",
            icon: <CiCircleList />,
            permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
            path: "/dashboards/help-center",
          },
          {
            id: "tt-help-center-parent",
            title: "Tam Tam Help Center Parent",
            messageId: "common.categories",
            icon: <BiSolidCategoryAlt />,
            permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
            path: "/dashboards/help-center/parent",
          },
          {
            id: "tt-help-center-child",
            title: "Tam Tam Help Center Child",
            messageId: "common.subjects",
            icon: <MdSubject />,
            permittedRole: [UsersRolesEnums.ADMIN, UsersRolesEnums.MANAGER],
            path: "/dashboards/help-center/children",
          },
        ],
      },
    ],
  },
  // {
  //   id: "apps",
  //   title: "Apps",
  //   messageId: "sidebar.apps",
  //   type: "group",
  //   children: [
  //     {
  //       id: "mail",
  //       title: "Mail",
  //       messageId: "sidebar.apps.mail",
  //       count: 4,
  //       icon: <FiMail />,
  //       path: "/apps/mail/folder/inbox",
  //     },
  //     {
  //       id: "todo",
  //       title: "ToDo",
  //       messageId: "sidebar.apps.todo",
  //       count: 6,
  //       icon: <RiTodoLine />,
  //       color: "#48bb78",
  //       path: "/apps/todo/folder/all",
  //     },
  //     {
  //       id: "calender",
  //       title: "Calender",
  //       messageId: "sidebar.apps.calender",
  //       icon: <BiTask />,
  //       path: "/apps/calender/folder/all",
  //     },
  //     {
  //       id: "contact",
  //       title: "Contact",
  //       messageId: "sidebar.apps.contact",
  //       icon: <MdOutlineContactPhone />,
  //       path: "/apps/contact/folder/all",
  //     },
  //     {
  //       id: "chat",
  //       title: "Chat",
  //       icon: <BsChatDots />,
  //       messageId: "sidebar.apps.chat",
  //       path: "/apps/chat",
  //     },
  //     {
  //       id: "scrum-board",
  //       title: "Scrum Board",
  //       messageId: "sidebar.apps.scrumboard",
  //       icon: <MdOutlineDns />,
  //       path: "/apps/scrum-board",
  //     },
  //     {
  //       id: "wall",
  //       title: "Wall",
  //       messageId: "sidebar.apps.wall",
  //       icon: <CgFeed />,
  //       path: "/apps/wall",
  //     },
  //     {
  //       id: "ecommerce",
  //       title: "Ecommerce",
  //       messageId: "sidebar.ecommerce",
  //       icon: <BiCartAlt />,
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "products",
  //           title: "Products",
  //           messageId: "sidebar.ecommerce.products",
  //           path: "/ecommerce/products",
  //         },
  //         {
  //           id: "product_detail",
  //           title: "Product Detail",
  //           messageId: "sidebar.ecommerce.productDetail",
  //           path: "/ecommerce/product_detail",
  //         },
  //         {
  //           id: "orders",
  //           title: "Orders",
  //           messageId: "sidebar.ecommerce.orders",
  //           path: "/ecommerce/orders",
  //         },
  //         {
  //           id: "cart",
  //           title: "Cart",
  //           messageId: "sidebar.ecommerce.cart",
  //           path: "/ecommerce/cart",
  //         },
  //         {
  //           id: "checkout",
  //           title: "Checkout",
  //           messageId: "sidebar.ecommerce.checkout",
  //           path: "/ecommerce/checkout",
  //         },
  //         {
  //           id: "confirmation",
  //           title: "Confirmation",
  //           messageId: "sidebar.ecommerce.confirmation",
  //           path: "/ecommerce/confirmation",
  //         },
  //         {
  //           id: "invoice-1",
  //           title: "Invoice 1",
  //           messageId: "sidebar.ecommerce.invoice1",
  //           path: "/ecommerce/invoice-1",
  //         },
  //         {
  //           id: "invoice-2",
  //           title: "Invoice 2",
  //           messageId: "sidebar.ecommerce.invoice2",
  //           path: "/ecommerce/invoice-2",
  //         },
  //       ],
  //     },
  //     {
  //       id: "admin-ecommerce",
  //       title: "Ecommerce Admin",
  //       messageId: "sidebar.ecommerceAdmin",
  //       type: "collapse",
  //       icon: <GrUserAdmin />,
  //       children: [
  //         {
  //           id: "productListing",
  //           title: "Product Listing",
  //           messageId: "sidebar.ecommerceAdmin.productListing",
  //           path: "/ecommerce/product-listing",
  //         },
  //         {
  //           id: "addProducts",
  //           title: "Add Products",
  //           messageId: "sidebar.ecommerceAdmin.addProducts",
  //           path: "/ecommerce/add-products",
  //         },
  //         {
  //           id: "customers",
  //           title: "Customers",
  //           messageId: "sidebar.ecommerce.customers",
  //           path: "/ecommerce/customers",
  //         },
  //       ],
  //     },
  //     {
  //       id: "invoice",
  //       title: "Invoice",
  //       messageId: "sidebar.invoice",
  //       type: "collapse",
  //       icon: <TbFileInvoice />,
  //       children: [
  //         {
  //           id: "addInvoice",
  //           title: "Add Invoices",
  //           messageId: "sidebar.invoice.addInvoice",
  //           path: "/invoice/add-invoice",
  //         },
  //         {
  //           id: "invoices",
  //           title: "Invoices",
  //           messageId: "sidebar.invoice.home",
  //           path: "/invoice",
  //         },
  //         {
  //           id: "clients",
  //           title: "Clients",
  //           messageId: "sidebar.invoice.clients",
  //           path: "/invoice/clients",
  //         },
  //         {
  //           id: "settings",
  //           title: "Settings",
  //           messageId: "sidebar.invoice.settings",
  //           path: "/invoice/settings",
  //         },
  //       ],
  //     },
  //     {
  //       id: "blog",
  //       title: "Blog",
  //       messageId: "sidebar.pages.extraPages.blog",
  //       type: "collapse",
  //       icon: <BiRss />,
  //       children: [
  //         {
  //           id: "bloglist",
  //           title: "Blog List",
  //           messageId: "sidebar.pages.extraPages.blogList",
  //           path: "/extra-pages/blog",
  //         },
  //         {
  //           id: "blogdetail",
  //           title: "Blog Detail",
  //           messageId: "sidebar.pages.extraPages.blogDetail",
  //           path: "/extra-pages/blog/blog-details",
  //         },
  //         {
  //           id: "blogcreate",
  //           title: "Create Blog",
  //           messageId: "sidebar.pages.extraPages.blogCreate",
  //           path: "/extra-pages/blog/create-blog",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   id: "third-party",
  //   title: "Libs",
  //   messageId: "sidebar.libs",
  //   type: "group",
  //   children: [
  //     {
  //       id: "google-map",
  //       title: "Google Map",
  //       messageId: "sidebar.googleMap",
  //       icon: <FiMap />,
  //       path: "/third-party/google-map",
  //     },
  //     {
  //       id: "recharts",
  //       title: "Recharts",
  //       messageId: "sidebar.recharts",
  //       icon: <RiBarChart2Line />,
  //       path: "recharts",
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "area",
  //           title: "Area Chart",
  //           messageId: "sidebar.recharts.areaChart",
  //           path: "/third-party/recharts/area",
  //         },
  //         {
  //           id: "bar",
  //           title: "Bar Chart",
  //           messageId: "sidebar.recharts.barChart",
  //           path: "/third-party/recharts/bar",
  //         },
  //         {
  //           id: "composed",
  //           title: "Composed Chart",
  //           messageId: "sidebar.recharts.composedChart",
  //           path: "/third-party/recharts/composed",
  //         },
  //         {
  //           id: "line",
  //           title: "Line Chart",
  //           messageId: "sidebar.recharts.lineChart",
  //           path: "/third-party/recharts/line",
  //         },
  //         {
  //           id: "pie",
  //           title: "Pie Chart",
  //           messageId: "sidebar.recharts.pieChart",
  //           path: "/third-party/recharts/pie",
  //         },
  //         {
  //           id: "radar",
  //           title: "Radar Chart",
  //           messageId: "sidebar.recharts.radarChart",
  //           path: "/third-party/recharts/radar",
  //         },
  //         {
  //           id: "radial",
  //           title: "Radial Chart",
  //           messageId: "sidebar.recharts.radialChart",
  //           path: "/third-party/recharts/radial",
  //         },
  //         {
  //           id: "scatter",
  //           title: "Scatter Chart",
  //           messageId: "sidebar.recharts.scatterChart",
  //           path: "/third-party/recharts/scatter",
  //         },
  //         {
  //           id: "funnel",
  //           title: "Funnel Chart",
  //           messageId: "sidebar.recharts.funnelChart",
  //           path: "/third-party/recharts/funnel",
  //         },
  //         {
  //           id: "treemap",
  //           title: "Treemap Chart",
  //           messageId: "sidebar.recharts.treeChart",
  //           path: "/third-party/recharts/treemap",
  //         },
  //       ],
  //     },
  //     {
  //       id: "big-calendar",
  //       title: "Big Calendar",
  //       messageId: "sidebar.bigCalender",
  //       icon: <FaRegCalendarAlt />,
  //       path: "/third-party/calendar",
  //     },
  //     {
  //       id: "react-color",
  //       title: "React Color",
  //       messageId: "sidebar.reactColor",
  //       icon: <MdInvertColors />,
  //       path: "/third-party/react-color",
  //     },
  //     {
  //       id: "react-dropzone",
  //       title: "React Dropzone",
  //       messageId: "sidebar.reactDropzone",
  //       icon: <CgAttachment />,
  //       path: "/third-party/react-dropzone",
  //     },
  //     {
  //       id: "react-notification",
  //       title: "React Notification",
  //       messageId: "sidebar.reactNotification",
  //       icon: <IoMdNotificationsOutline />,
  //       path: "/third-party/react-notification",
  //     },
  //     {
  //       id: "react-gallery",
  //       title: "Gallery",
  //       messageId: "sidebar.gallery",
  //       icon: <FaRegImages />,
  //       path: "/third-party/react-gallery",
  //     },
  //     {
  //       id: "react-player",
  //       title: "Player",
  //       messageId: "sidebar.player",
  //       icon: <DiHtml5Multimedia />,
  //       path: "/third-party/react-player",
  //     },
  //     {
  //       id: "time-line",
  //       title: "Time Line",
  //       messageId: "sidebar.pages.timeLine",
  //       icon: <MdTimeline />,
  //       path: "/third-party/time-line",
  //     },
  //   ],
  // },
  // {
  //   id: "components",
  //   title: "Components",
  //   messageId: "sidebar.components",
  //   type: "group",
  //   children: [
  //     {
  //       id: "general",
  //       title: "General",
  //       messageId: "sidebar.components.general",
  //       icon: <TiMap />,
  //       path: "general",
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "button",
  //           title: "Button",
  //           messageId: "sidebar.general.button",
  //           path: "/components/general/button",
  //         },
  //         {
  //           id: "typography",
  //           title: "Typography",
  //           messageId: "sidebar.general.typography",
  //           path: "/components/general/typography",
  //         },
  //         {
  //           id: "icon",
  //           title: "Icon",
  //           messageId: "sidebar.general.icon",
  //           path: "/components/general/icon",
  //         },
  //       ],
  //     },
  //     {
  //       id: "navigation",
  //       title: "Navigation",
  //       messageId: "sidebar.components.navigation",
  //       icon: <RiEqualizerLine />,
  //       path: "navigation",
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "affix",
  //           title: "Affix",
  //           messageId: "sidebar.navigation.affix",
  //           path: "/components/navigation/affix",
  //         },
  //         {
  //           id: "breadcrumb",
  //           title: "Breadcrumb",
  //           messageId: "sidebar.navigation.breadcrumb",
  //           path: "/components/navigation/breadcrumb",
  //         },
  //         {
  //           id: "dropdown",
  //           title: "Dropdown",
  //           messageId: "sidebar.navigation.dropdown",
  //           path: "/components/navigation/dropdown",
  //         },
  //         {
  //           id: "menu",
  //           title: "Menu",
  //           messageId: "sidebar.navigation.menu",
  //           path: "/components/navigation/menu",
  //         },
  //         {
  //           id: "page-header",
  //           title: "PageHeader",
  //           messageId: "sidebar.navigation.pageHeader",
  //           path: "/components/navigation/page-header",
  //         },
  //         {
  //           id: "pagination",
  //           title: "Pagination",
  //           messageId: "sidebar.navigation.pagination",
  //           path: "/components/navigation/pagination",
  //         },
  //         {
  //           id: "steps",
  //           title: "Steps",
  //           messageId: "sidebar.navigation.steps",
  //           path: "/components/navigation/steps",
  //         },
  //       ],
  //     },
  //     {
  //       id: "dataEntry",
  //       title: "Data Entry",
  //       messageId: "sidebar.components.dataEntry",
  //       icon: <AiOutlineDatabase />,
  //       path: "dataEntry",
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "auto-complete",
  //           title: "AutoComplete",
  //           messageId: "sidebar.dataEntry.autoComplete",
  //           path: "/components/dataEntry/auto-complete",
  //         },
  //         {
  //           id: "checkbox",
  //           title: "Checkbox",
  //           messageId: "sidebar.dataEntry.checkbox",
  //           path: "/components/dataEntry/checkbox",
  //         },
  //         {
  //           id: "cascader",
  //           title: "Cascader",
  //           messageId: "sidebar.dataEntry.cascader",
  //           path: "/components/dataEntry/cascader",
  //         },
  //         {
  //           id: "date-picker",
  //           title: "Datepicker",
  //           messageId: "sidebar.dataEntry.datePicker",
  //           path: "/components/dataEntry/date-picker",
  //         },
  //         {
  //           id: "form",
  //           title: "Form",
  //           messageId: "sidebar.dataEntry.form",
  //           path: "/components/dataEntry/form",
  //         },
  //         {
  //           id: "inputNumber",
  //           title: "InputNumber",
  //           messageId: "sidebar.dataEntry.inputNumber",
  //           path: "/components/dataEntry/inputNumber",
  //         },
  //         {
  //           id: "input",
  //           title: "Input",
  //           messageId: "sidebar.dataEntry.input",
  //           path: "/components/dataEntry/input",
  //         },
  //         {
  //           id: "mention",
  //           title: "Mention",
  //           messageId: "sidebar.dataEntry.mention",
  //           path: "/components/dataEntry/mention",
  //         },
  //         {
  //           id: "rate",
  //           title: "Rate",
  //           messageId: "sidebar.dataEntry.rate",
  //           path: "/components/dataEntry/rate",
  //         },
  //         {
  //           id: "radio",
  //           title: "Radio",
  //           messageId: "sidebar.dataEntry.radio",
  //           path: "/components/dataEntry/radio",
  //         },
  //         {
  //           id: "switch",
  //           title: "Switch",
  //           messageId: "sidebar.dataEntry.switch",
  //           path: "/components/dataEntry/switch",
  //         },
  //         {
  //           id: "slider",
  //           title: "Slider",
  //           messageId: "sidebar.dataEntry.slider",
  //           path: "/components/dataEntry/slider",
  //         },
  //         {
  //           id: "select",
  //           title: "Select",
  //           messageId: "sidebar.dataEntry.select",
  //           path: "/components/dataEntry/select",
  //         },
  //         {
  //           id: "tree-select",
  //           title: "TreeSelect",
  //           messageId: "sidebar.dataEntry.treeSelect",
  //           path: "/components/dataEntry/tree-select",
  //         },
  //         {
  //           id: "transfer",
  //           title: "Transfer",
  //           messageId: "sidebar.dataEntry.transfer",
  //           path: "/components/dataEntry/transfer",
  //         },
  //         {
  //           id: "time-picker",
  //           title: "Time Picker",
  //           messageId: "sidebar.dataEntry.timePicker",
  //           path: "/components/dataEntry/time-picker",
  //         },
  //         {
  //           id: "upload",
  //           title: "Upload",
  //           messageId: "sidebar.dataEntry.upload",
  //           path: "/components/dataEntry/upload",
  //         },
  //       ],
  //     },
  //     {
  //       id: "dataDisplay",
  //       title: "Data Display",
  //       messageId: "sidebar.components.dataDisplay",
  //       icon: <BiData />,
  //       path: "dataDisplay",
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "avatar",
  //           title: "Avatar",
  //           messageId: "sidebar.dataDisplay.avatar",
  //           path: "/components/dataDisplay/avatar",
  //         },
  //         {
  //           id: "badge",
  //           title: "Badge",
  //           messageId: "sidebar.dataDisplay.badge",
  //           path: "/components/dataDisplay/badge",
  //         },
  //         {
  //           id: "collapse",
  //           title: "Collapse",
  //           messageId: "sidebar.dataDisplay.collapse",
  //           path: "/components/dataDisplay/collapse",
  //         },
  //         {
  //           id: "carousel",
  //           title: "Carousel",
  //           messageId: "sidebar.dataDisplay.carousel",
  //           path: "/components/dataDisplay/carousel",
  //         },
  //         {
  //           id: "card",
  //           title: "Card",
  //           messageId: "sidebar.dataDisplay.card",
  //           path: "/components/dataDisplay/card",
  //         },
  //         {
  //           id: "calendar",
  //           title: "Calendar",
  //           messageId: "sidebar.dataDisplay.calender",
  //           path: "/components/dataDisplay/calendar",
  //         },
  //         {
  //           id: "list",
  //           title: "List",
  //           messageId: "sidebar.dataDisplay.list",
  //           path: "/components/dataDisplay/list",
  //         },
  //         {
  //           id: "popover",
  //           title: "Popover",
  //           messageId: "sidebar.dataDisplay.popover",
  //           path: "/components/dataDisplay/popover",
  //         },
  //         {
  //           id: "tree",
  //           title: "Tree",
  //           messageId: "sidebar.dataDisplay.tree",
  //           path: "/components/dataDisplay/tree",
  //         },
  //         {
  //           id: "tooltip",
  //           title: "Tooltips",
  //           messageId: "sidebar.dataDisplay.toolTips",
  //           path: "/components/dataDisplay/tooltip",
  //         },
  //         {
  //           id: "timeline",
  //           title: "Timeline",
  //           messageId: "sidebar.dataDisplay.timeLine",
  //           path: "/components/dataDisplay/timeline",
  //         },
  //         {
  //           id: "tag",
  //           title: "Tag",
  //           messageId: "sidebar.dataDisplay.tag",
  //           path: "/components/dataDisplay/tag",
  //         },
  //         {
  //           id: "tabs",
  //           title: "Tabs",
  //           messageId: "sidebar.dataDisplay.tabs",
  //           path: "/components/dataDisplay/tabs",
  //         },
  //         {
  //           id: "comment",
  //           title: "Comment",
  //           messageId: "sidebar.dataDisplay.comment",
  //           path: "/components/dataDisplay/comment",
  //         },
  //         {
  //           id: "descriptions",
  //           title: "Descriptions",
  //           messageId: "sidebar.dataDisplay.descriptions",
  //           path: "/components/dataDisplay/descriptions",
  //         },
  //         {
  //           id: "empty",
  //           title: "Empty",
  //           messageId: "sidebar.dataDisplay.empty",
  //           path: "/components/dataDisplay/empty",
  //         },
  //         {
  //           id: "image",
  //           title: "Image",
  //           messageId: "sidebar.dataDisplay.image",
  //           path: "/components/dataDisplay/image",
  //         },
  //         {
  //           id: "statistic",
  //           title: "Statistic",
  //           messageId: "sidebar.dataDisplay.statistic",
  //           path: "/components/dataDisplay/statistic",
  //         },
  //       ],
  //     },

  //     {
  //       id: "feedBack",
  //       title: "FeedBack",
  //       messageId: "sidebar.components.feedBack",
  //       icon: <VscFeedback />,
  //       path: "feedBack",
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "alert",
  //           title: "Alert",
  //           messageId: "sidebar.feedBack.alert",
  //           path: "/components/feedBack/alert",
  //         },
  //         {
  //           id: "modal",
  //           title: "Modal",
  //           messageId: "sidebar.feedBack.modal",
  //           path: "/components/feedBack/modal",
  //         },
  //         {
  //           id: "message",
  //           title: "Message",
  //           messageId: "sidebar.feedBack.message",
  //           path: "/components/feedBack/message",
  //         },
  //         {
  //           id: "notification",
  //           title: "Notification",
  //           messageId: "sidebar.feedBack.notification",
  //           path: "/components/feedBack/notification",
  //         },
  //         {
  //           id: "progress",
  //           title: "Progress",
  //           messageId: "sidebar.feedBack.progress",
  //           path: "/components/feedBack/progress",
  //         },
  //         {
  //           id: "pop-confirm",
  //           title: "PopConfirm",
  //           messageId: "sidebar.feedBack.popConfirm",
  //           path: "/components/feedBack/pop-confirm",
  //         },
  //         {
  //           id: "spin",
  //           title: "Spin",
  //           messageId: "sidebar.feedBack.spin",
  //           path: "/components/feedBack/spin",
  //         },
  //         {
  //           id: "drawer",
  //           title: "Drawer",
  //           messageId: "sidebar.feedBack.drawer",
  //           path: "/components/feedBack/drawer",
  //         },
  //         {
  //           id: "result",
  //           title: "Result",
  //           messageId: "sidebar.feedBack.result",
  //           path: "/components/feedBack/result",
  //         },
  //         {
  //           id: "skeleton",
  //           title: "Skeleton",
  //           messageId: "sidebar.feedBack.skeleton",
  //           path: "/components/feedBack/skeleton",
  //         },
  //       ],
  //     },
  //     {
  //       id: "other",
  //       title: "Other",
  //       messageId: "sidebar.components.other",
  //       icon: <MdDevicesOther />,
  //       path: "other",
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "anchor",
  //           title: "Anchor",
  //           messageId: "sidebar.other.anchor",
  //           path: "/components/other/anchor",
  //         },
  //         {
  //           id: "backTop",
  //           title: "BackTop",
  //           messageId: "sidebar.other.backTop",
  //           path: "/components/other/backTop",
  //         },
  //         {
  //           id: "divider",
  //           title: "Divider",
  //           messageId: "sidebar.other.divider",
  //           path: "/components/other/divider",
  //         },
  //         {
  //           id: "config-provider",
  //           title: "ConfigProvider",
  //           messageId: "sidebar.other.configProvider",
  //           path: "/components/other/config-provider",
  //         },
  //       ],
  //     },
  //     {
  //       id: "layout",
  //       title: "Layout",
  //       messageId: "sidebar.components.layout",
  //       icon: <AiOutlineLayout />,
  //       path: "layout",
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "layout-divider",
  //           title: "Divider",
  //           messageId: "sidebar.layout.divider",
  //           path: "/components/layout/divider",
  //         },
  //         {
  //           id: "space",
  //           title: "Space",
  //           messageId: "sidebar.layout.space",
  //           path: "/components/layout/space",
  //         },
  //       ],
  //     },
  //     {
  //       id: "table",
  //       title: "Table",
  //       messageId: "sidebar.dataDisplay.table",
  //       icon: <BsTable />,
  //       path: "table",
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "basic-table",
  //           title: "Basic",
  //           messageId: "sidebar.bigCalender.basic",
  //           path: "/components/table/basic-table",
  //         },
  //         {
  //           id: "data",
  //           title: "Data",
  //           messageId: "sidebar.table.data",
  //           path: "/components/table/data",
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   id: "extra-pages",
  //   title: "Extra Pages",
  //   messageId: "sidebar.pages.extraPages",
  //   path: "extra-pages",
  //   type: "group",
  //   children: [
  //     {
  //       id: "account",
  //       title: "Account",
  //       messageId: "sidebar.pages.extraPages.account",
  //       icon: <MdOutlineManageAccounts />,
  //       path: "/extra-pages/account",
  //     },
  //     {
  //       id: "about-us",
  //       title: "About Us",
  //       messageId: "sidebar.pages.extraPages.aboutUs",
  //       icon: <FiUsers />,
  //       path: "/extra-pages/about-us",
  //     },
  //     {
  //       id: "contact-us",
  //       title: "Contact Us",
  //       messageId: "sidebar.pages.extraPages.contactUs",
  //       icon: <MdOutlineContactSupport />,
  //       path: "/extra-pages/contact-us",
  //     },
  //     {
  //       id: "knowledge-base",
  //       title: "Knowledge Base",
  //       messageId: "sidebar.pages.extraPages.knowledgeBase",
  //       icon: <BiBookReader />,
  //       path: "/extra-pages/knowledge-base",
  //     },
  //     {
  //       id: "portfolio",
  //       title: "Portfolio",
  //       messageId: "sidebar.pages.extraPages.portfolio",
  //       icon: <BsBriefcase />,
  //       path: "/extra-pages/portfolio",
  //     },
  //     {
  //       id: "faq",
  //       title: "FAQ",
  //       messageId: "sidebar.pages.extraPages.faq",
  //       icon: <BsQuestionDiamond />,
  //       path: "/extra-pages/faq",
  //     },
  //     {
  //       id: "pricing",
  //       title: "Pricing",
  //       messageId: "sidebar.pages.extraPages.pricing",
  //       type: "collapse",
  //       icon: <BiDollar />,
  //       children: [
  //         {
  //           id: "pricingListing",
  //           title: "Pricing Listing",
  //           messageId: "sidebar.pages.extraPages.pricingListing",
  //           path: "/extra-pages/pricing-listing",
  //         },
  //         {
  //           id: "pricingDetail",
  //           title: "Pricing Detail",
  //           messageId: "sidebar.pages.extraPages.pricingDetail",
  //           path: "/extra-pages/pricing-detail",
  //         },
  //       ],
  //     },
  //     {
  //       id: "user",
  //       title: "user Pages",
  //       messageId: "sidebar.pages.userPages",
  //       icon: <RiShieldUserLine />,
  //       path: "user",
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "sign-in-1",
  //           title: "SignIn-1",
  //           messageId: "sidebar.pages.userPages.signIn1",
  //           path: "/user/sign-in-1",
  //         },
  //         {
  //           id: "sign-in-2",
  //           title: "SignIn-2",
  //           messageId: "sidebar.pages.userPages.signIn2",
  //           path: "/user/sign-in-2",
  //         },
  //         {
  //           id: "sign-up-1",
  //           title: "SignUp-1",
  //           messageId: "sidebar.pages.userPages.signUp1",
  //           path: "/user/sign-up-1",
  //         },
  //         {
  //           id: "sign-up-2",
  //           title: "SignUp-2",
  //           messageId: "sidebar.pages.userPages.signUp2",
  //           path: "/user/sign-up-2",
  //         },
  //         {
  //           id: "forgot-password-1",
  //           title: "Forgot Password-1",
  //           messageId: "sidebar.pages.userPages.forgetPassword1",
  //           path: "/user/forgot-password-1",
  //         },
  //         {
  //           id: "forgot-password-2",
  //           title: "Forgot Password-2",
  //           messageId: "sidebar.pages.userPages.forgetPassword2",
  //           path: "/user/forgot-password-2",
  //         },
  //         {
  //           id: "reset-password-1",
  //           title: "Reset Password-1",
  //           messageId: "sidebar.pages.userPages.resetPassword1",
  //           path: "/user/reset-password-1",
  //         },
  //         {
  //           id: "reset-password-2",
  //           title: "Reset Password-2",
  //           messageId: "sidebar.pages.userPages.resetPassword2",
  //           path: "/user/reset-password-2",
  //         },
  //         {
  //           id: "lock-1",
  //           title: "Lock Screen-1",
  //           messageId: "sidebar.pages.userPages.lockScreen1",
  //           path: "/user/lock-1",
  //         },
  //         {
  //           id: "lock-2",
  //           title: "Lock Screen-2",
  //           messageId: "sidebar.pages.userPages.lockScreen2",
  //           path: "/user/lock-2",
  //         },
  //       ],
  //     },
  //     {
  //       id: "list-type",
  //       title: "user List",
  //       messageId: "sidebar.pages.userList",
  //       icon: <CgUserList />,
  //       path: "list-type",
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "morden",
  //           title: "Modern",
  //           messageId: "sidebar.pages.userList.modern",
  //           path: "/list-type/modern",
  //         },
  //         {
  //           id: "standard",
  //           title: "Standard",
  //           messageId: "sidebar.pages.userList.standard",
  //           path: "/list-type/standard",
  //         },
  //         {
  //           id: "flat",
  //           title: "Flat",
  //           messageId: "sidebar.pages.userList.flat",
  //           path: "/list-type/flat",
  //         },
  //       ],
  //     },
  //     {
  //       id: "error-pages",
  //       title: "Error Pages",
  //       messageId: "sidebar.pages.errorPages",
  //       icon: <BiErrorCircle />,
  //       path: "error-pages",
  //       type: "collapse",
  //       children: [
  //         {
  //           id: "error-401",
  //           title: "401",
  //           messageId: "sidebar.pages.errorPages.401",
  //           path: "/error-pages/error-401",
  //         },
  //         {
  //           id: "error-403",
  //           title: "403",
  //           messageId: "sidebar.pages.errorPages.403",
  //           path: "/error-pages/error-403",
  //         },
  //         {
  //           id: "error-404",
  //           title: "404",
  //           messageId: "sidebar.pages.errorPages.404",
  //           path: "/error-pages/error-404",
  //         },
  //         {
  //           id: "error-500",
  //           title: "500",
  //           messageId: "sidebar.pages.errorPages.500",
  //           path: "/error-pages/error-500",
  //         },
  //         {
  //           id: "maintenance",
  //           title: "Maintenance",
  //           messageId: "sidebar.pages.errorPages.maintenance",
  //           path: "/error-pages/maintenance",
  //         },
  //         {
  //           id: "coming-soon",
  //           title: "Coming Soon",
  //           messageId: "sidebar.pages.errorPages.comingSoon",
  //           path: "/error-pages/coming-soon",
  //         },
  //       ],
  //     },
  //   ],
  // },
];
export default routesConfig;
